== Cake Jambon Olives

Ingrédients pour 4 personnes

- 6 oeufs
- 320 g de farine 
- 250 g de beurre pommade + 20 g pour le moule
- 5 g de levure chimique
- 150 g d'olives dénoyautées
- 150 g de jambon en une seule tranche
- 100 g de beaufort
- sel fin, poivre.

== Etapes de préparation

1. Taillez en dés le jambon et le beaufort. Coupez en deux les olives.
2. Préparez la pâte: incorporez au batteur les oeufs dans le beurre petit à petit pour que le mélange soit bien émulsionné. Mélangez avec 300 g de farine tamisée avec la levure, du sel et du poivre. Lorsque la pâte est lisse, incorporez le jambon, les olives et le fromage.
3. Versez la pâte dans un (ou deux) moule à cake beurré et fariné, faites cuire au four 1 h 15 (ou moins si vous utilisez 2 moules) à th 7 (210°C); baissez si nécessaire en cours de cuisson et couvrez si le cake colore trop rapidement en surface. Démoulez et laissez refroidir sur grille.
4. Coupez en tranches. Accompagnez d'une salade croquante, assaisonnée d'une vinaigrette à l'huile de noix, et agrémentée de quelques oignons frits.

== Astuces et conseils

Utilisez soit des olives noires, soit des vertes dénoyautées, ou mélangez les deux sortes d'olives.

Cette recette est aussi présente dans Enfant, Familiale, Buffet, Recette traditionnelle, Entrée, Flan salé, Cake aux olives
